foody/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^foody_1/", include("foody_1.urls", namespace="foody_1")),
    url(r"^seller/", include("seller.urls", namespace="seller")),
    url(r"^foody_1/", include("django.contrib.auth.urls")),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),


]

foody_1/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'foody_1'

urlpatterns = [
    url(r"^login/$", auth_views.LoginView.as_view(template_name="foody_1/login.html"),name='login'),
    url(r"^northindian/$", views.NorthIndianView.as_view(), name="northindian"),
    url(r"^southindian/$", views.SouthIndianView.as_view(), name="southindian"),
    url(r"^italian/$", views.ItalianView.as_view(), name="italian"),
    url(r"^chinese/$", views.ChineseView.as_view(), name="chinese"),
    url(r"^continental/$", views.ContinentalView.as_view(), name="continental"),
    url(r"^fastfood/$", views.FastFoodView.as_view(), name="fastfood"),
    url(r"^beverages/$", views.beveragesView.as_view(), name="bev"),
    url(r"^deserts/$", views.desView.as_view(), name="des"),
    url(r"^confused/$", views.ConfusedView.as_view(), name="confused"),
    url(r"^logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"^signup/$", views.SignUp.as_view(), name="signup"),
    url(r"^result/$", views.resultpage, name="result"),


    url(r"^confused/happy/$", views.HappyView, name="happy"),
    url(r"^confused/angry/$", views.AngryView, name="angry"),
    url(r"^confused/dehydrate/$", views.DehydrateView, name="dehydrate"),
    url(r"^confused/depress/$", views.DepressiveView, name="depress"),
    url(r"^confused/excite/$", views.ExciteView, name="excite"),
    url(r"^confused/unwell/$", views.UnwellView, name="unwell"),


    url(r"^chinese/noodles/$", views.ChineseNoodlesView, name="noodles"),
    url(r"^chinese/chillyPaneer/$", views.ChineseChillyPaneerView, name="chillyPaneer"),


    url(r"^continental/ham/$", views.ContinentalHamView, name="ham"),
    url(r"^continental/springroll/$", views.ContinentalSpringRollView, name="springroll"),



    url(r"^northindian/chollebature/$", views.NorthIndianCholleView, name="cholle"),
    url(r"^northindian/rajmachawal/$", views.NorthIndianRajmaView, name="rajma"),


    url(r"^southindian/dosa/$", views.SouthIndianDosaView, name="dosa"),
    url(r"^southindian/idli/$", views.SouthIndianIdliView, name="idli"),


    url(r"^italian/garlicbread/$", views.ItalianGarlicView, name="garlic"),
    url(r"^italian/pasta/$", views.ItalianPastaView, name="pasta"),



    url(r"^fastfood/aalootikki/$", views.FastFoodAalooView, name="aalootikki"),
    url(r"^fastfood/vadapao/$", views.FastFoodPaoView, name="vadapao"),


# deserts
    url(r"^deserts/icecream/$", views.IcecreamView, name="icecream"),
    url(r"^deserts/pastries/$", views.PastriesView, name="pastries"),
    url(r"^deserts/chocolates/$", views.ChocolatesView, name="chocolates"),

# beverages
    url(r"^beverages/tea/$", views.TeaView, name="tea"),
    url(r"^beverages/softdrinks/$", views.softdrinksView, name="softdrinks"),
    url(r"^beverages/juices/$", views.juicesView, name="juices"),


    ]

seller/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'seller'

urlpatterns=[
    url(r"^seller_form/$", views.seller_form.as_view(), name="seller_form"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Foody</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Cairo" rel="stylesheet">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.6.4.slim.min.js" integrity="sha256-a2yjHM4jnF9f54xUQakjZGaqYs/V1CYvWpoqZzC2/Bw=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">


    {% block headblock %}
    {% endblock %}

  </head>
  <body>
    <nav class="navbar mynav" role="navigation" id="navbar">
    			<div class="container">
            {% if user.is_authenticated %}
            <a class="navbar-brand btn btn-default" href="{% url 'test' %}">
              <span class='glyphicon glyphicon-home'>

               </span>
            </a>
               {% else %}
            <a class="navbar-brand btn btn-default" href="{% url 'home' %}">
              <span class='glyphicon glyphicon-home'>

               </span>
            </a>
              {% endif %}
    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                    <li><a href="{% url 'foody_1:logout' %}"><button type="button" class="btn btn-primary">LogOut</button></a></li>
    						{% else %}
                      <li><a href="{% url 'foody_1:login' %}"><button type="button" class="btn btn-primary">Login</button></a></li>
                      <li><p></p></li>
    						      <li><a href="{% url 'foody_1:signup' %}"><button type="button" class="btn btn-primary">Sign Up</button></a></li>
    						{% endif %}
    					</ul>
    			</div>
    		</nav>
        {% block fullscreen %}
        {% endblock %}
        <div class="container mycontent">
          {% block content %}

          {% endblock %}
        </div>

  <canvas id="canvas"></canvas>
  <style>
    body{
      background-color: #ffe1ef !important;
    }
    .nav>li>a:hover, .nav>li>a:focus {
      background-color: #ffe1ef !important;
    }
  </style>
  </body>

</html>

templates/index.html
{% extends "base.html" %}
{% block headblock %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}

<div class="index-banner">
  <div class="index-banner-bg"><img src="https://images.unsplash.com/photo-1560801619-01d71da0f70c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" alt="banner" /></div>
  <div class="index-banner-text">
      <h1 align="center" class="head_mansi">MOODIE FOODIE</h1>
    <div class="text-logo"></div>
    <p class="text-info">
      <i class="line line-left"></i>

      <span class="under_tag">The first food recommending and delivery app that gives your mood the prime importance</span><i class="line line-right"></i>
    </p>
  </div>
</div>
<br>
<br>
{% if not user.is_authenticated %}

<a href="{% url 'seller:seller_form' %}" class='sell' >Wanna sell on Moodie Foodie?</a>
{% endif %}

<style media="screen">
.sell{
  text-align: center;
    display:block;
  font-size: 30px;
font-family: 'Poor Story', cursive;
}
.under_tag{
  color:white;
  font-size: 25px;
  font-family: 'Poor Story', cursive;
}
.head_mansi{

  color:white;
  font-size: 100px;
  font-family: 'Poor Story', cursive;
}
.index-banner {
  position: relative;
  background: #b3b3b3;
}
.index-banner-bg {
  height: 500px;
  overflow: hidden;
}
.index-banner-bg img {
  object-fit: cover;
  object-position: center;
  aspect-ratio: 16/9;
  height: 100%;
  width: 100%;
  filter: brightness(50%);
}
.index-banner-text {
  position: absolute;
  top: 100px;
  left: 50%;
   margin-left: -430px;
}
.index-banner-text .text-logo {
  width: 776px;
  height: 117px;

  no-repeat;
}
.index-banner-text .text-info {
  margin-top: 10px;
  text-align: center;
  color: #fff;
}
.index-banner-text .text-info .line {
  display: inline-block;
  width: 40px;
  border-top: 1px solid #fff;
  vertical-align: middle;
  *margin-top: 22px;
}
.index-banner-text .text-info .text {
  margin: 0 26px;
}


.index-panel {
  margin: 0 auto;
  margin-top: 200px;
  position: relative;
  width: 1100px;
}
.inedx-panel-header {
}
.inedx-panel-header h3 {
  float: left;
  margin-right: 48px;
  font-size: 20px;
  color: #3b3b3b;
  font-weight: normal;
}
.inedx-panel-header .line {
  float: left;
  margin-top: 10px;
  width: 200px;
  border-top: 1px solid #e5e3e3;
}
.inedx-panel-header .btn-group {
  font-size: 0;
  float: right;
}
.inedx-panel-header .btn {
  display: inline-block;
  margin-left: 11px;
  width: 9px;
  height: 9px;
  background: #dedede;
  border-radius: 50%;
  -moz-border-radius: 50%;
  -webkit-border-radius: 50%;
}
.inedx-panel-header .active {
  background: #9b9b9b;
}
.index-panel-body {
  margin-top: 75px;
}
.index-food-list {
  overflow: hidden;
}
.index-food-list ul {
  width: 1160px;
}
.index-food-list .food-item {
  float: left;
  width: 230px;
  margin-right: 60px;
}
.index-food-list .food-item .banner {
  margin-bottom: 30px;
  height: 202px;
}
.index-food-list .food-item .name {
  color: #555;
  margin-bottom: 10px;
}
.index-food-list .food-item .star-bar {
  font-size: 0;
}
.index-food-list .food-item .star {
  display: inline-block;
  width: 12px;
  height: 13px;
  margin-right: 5px;
  background-image: url("https://github.com/JessicaPotter2/foodWebsite/blob/master/images/star.png?raw=true");
  background-repeat: no-repeat;
}
.index-food-list .food-item .no-star {
  background-position: 0 -13px;
}
.index-food-list .food-item .price {
  float: right;
}
.index-pics {
  height: 380px;
  overflow: hidden;
}
.index-pics .pic-col {
  float: left;
}
.index-pics .pic-col-l {
  width: 460px;
}
.index-pics .pic-col-m {
  width: 352px;
}
.index-pics .pic-col-s {
  width: 288px;
}
.public-header {
  height: 110px;
}
.public-header .header-logo {
  margin-top: 40px;
  float: left;
}
.public-header .header-logo a {
  width: 182px;
  height: 54px;
  background: url("https://github.com/JessicaPotter2/foodWebsite/blob/master/images/index-header-logo.png?raw=true")
    no-repeat;
}
.public-header .header-nav a:hover {
  text-decoration: underline;
}
.public-header .header-nav {
  float: right;
  font-size: 14px;
}
.public-header .header-nav .item {
  float: left;
  margin-top: 44px;
  margin-left: 44px;
}
.public-header .header-nav a {
  color: #3b3b3b;
}
.public-container {
  position: relative;
  margin: 0 auto;
  width: 1100px;
}
.public-footer {
  height: 218px;
  padding-top: 100px;
  margin-top: 200px;
  background: #3b3b3b;
}
.public-footer .footer-col {
  width: 230px;
  float: left;
  margin-right: 60px;
  font-size: 16px;
  color: #fff;
  line-height: 1.8;
}
.public-footer .footer-col-nor {
  margin-right: 0;
}
.public-footer .footer-logo {
  width: 182px;
  height: 55px;
  margin-top: -15px;
  margin-bottom: 12px;
  background: url("https://github.com/JessicaPotter2/foodWebsite/blob/master/images/index-footer-logo.png?raw=true")
    no-repeat;
}
.footer-info a {
  display: inline-block;
  font-size: 18px;
  font-weight: bold;
}

</style>

{% endblock %}

templates/test.html
{% extends "base.html" %}
{% load static %}
{% block headblock %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}
<div class="container">
  <h2 align='center' class='confused'>Cuisines</h2>
  <div class="row">
    <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:northindian' %}"><img class="img" src="https://images.unsplash.com/photo-1617692855027-33b14f061079?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8" style="object-fit:unset" alt="">North Indian</div>
    <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:southindian' %}"><img class="img" src="https://images.unsplash.com/photo-1589301760014-d929f3979dbc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format" alt="">South Indian</div>
    <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:italian' %}"><img class="img" src="https://images.unsplash.com/photo-1506280754576-f6fa8a873550?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format" alt="">Italian</div>
    <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:chinese' %}"><img class="img" src="https://images.unsplash.com/flagged/photo-1556742524-750f2ab99913?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx" alt="">Chinese</div>
    <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:confused' %}"><img class="img" style="object-fit:contain" src="https://i.imgur.com/qnTo8MC.jpeg" alt="">  Feelin MOODIE? Can't decide? We can help! :D</div>
    <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:continental' %}"><img class="img" style="object-fit:unset" src="https://images.unsplash.com/photo-1535567465397-7523840f2ae9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx" alt="">Continental</div>
    <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:fastfood' %}"><img class="img" src="https://images.unsplash.com/photo-1505826759037-406b40feb4cd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8" alt="">Fast Food</div>
    <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:bev' %}"><img class="img" src="https://images.unsplash.com/photo-1496318447583-f524534e9ce1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format" alt="">Beverages</div>
    <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:des' %}"><img class="img" src="https://images.unsplash.com/photo-1624353365286-3f8d62daad51?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" alt="">Desserts</div>
  </div>
</div>
<style media="screen">
  .hello{
    font-size: 20px;
    text-align: center;
      display:block;
      height: 320px;
      width: 370px;
      margin: auto;
  }
  .img{
    height: 250px !important;
    width: 400px;
    object-fit: cover;
    object-position: center;
    border-radius: 10px;
    aspect-ratio: 1 / 1;
  }
  .confused{
    font-size: 50px;
    text-align: center;
    font-family: 'Poor Story', cursive;
  }
</style>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% load static %}
{% block headblock %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">

<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}
<h1 class='head_mansi'>THANKS</h1>


<style media="screen">
.link{
  text-align: center;
    display: block;
  font-size: 30px;
font-family: 'Poor Story', cursive;
}
.under_tag{
  color:black;
  font-size: 25px;
  font-family: 'Poor Story', cursive;
}
.head_mansi{

  color:black;
  font-size: 100px;
  text-align: center;
  font-family: 'Poor Story', cursive;
}
</style>
{% endblock %}